# Generated by Django 5.2.7 on 2025-11-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabelTaskModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="任务编号"
                    ),
                ),
                ("user_id", models.IntegerField(verbose_name="创建人ID")),
                ("username", models.CharField(max_length=100, verbose_name="创建人")),
                ("name", models.CharField(max_length=50, verbose_name="任务名称")),
                (
                    "remark",
                    models.TextField(blank=True, null=True, verbose_name="备注"),
                ),
                (
                    "source_video_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="源视频物理路径",
                    ),
                ),
                (
                    "patient_data_path",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        null=True,
                        verbose_name="加密病例路径",
                    ),
                ),
                ("video_fps", models.IntegerField(default=30, verbose_name="抽帧帧率")),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="是否已处理"),
                ),
                (
                    "sample_count",
                    models.IntegerField(default=0, verbose_name="样本总数"),
                ),
                (
                    "sample_annotation_count",
                    models.IntegerField(default=0, verbose_name="已标注数"),
                ),
                ("state", models.IntegerField(default=0, verbose_name="状态")),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "create_timestamp",
                    models.IntegerField(default=0, verbose_name="时间戳"),
                ),
                (
                    "last_update_time",
                    models.DateTimeField(auto_now=True, verbose_name="最后更新"),
                ),
            ],
            options={
                "verbose_name": "任务与病例",
                "verbose_name_plural": "任务与病例",
                "db_table": "xcnvs_label_task",
            },
        ),
        migrations.CreateModel(
            name="LabelTkSampleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sort", models.IntegerField(default=0, verbose_name="排序")),
                ("code", models.CharField(max_length=50, verbose_name="样本编号")),
                (
                    "task_code",
                    models.CharField(
                        db_index=True, max_length=50, verbose_name="所属任务编号"
                    ),
                ),
                (
                    "old_filename",
                    models.CharField(max_length=200, verbose_name="脱敏文件名"),
                ),
                (
                    "new_filename",
                    models.CharField(max_length=200, verbose_name="相对路径"),
                ),
                (
                    "annotation_content",
                    models.TextField(blank=True, null=True, verbose_name="标注数据"),
                ),
                (
                    "annotation_state",
                    models.IntegerField(default=0, verbose_name="标注状态"),
                ),
                (
                    "annotation_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="标注时间"
                    ),
                ),
                (
                    "annotation_username",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="标注员"
                    ),
                ),
                (
                    "create_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                ("task_type", models.IntegerField(default=1)),
                ("state", models.IntegerField(default=1)),
            ],
            options={
                "verbose_name": "样本图片",
                "verbose_name_plural": "样本图片",
                "db_table": "xcnvs_labeltk_sample",
            },
        ),
    ]
